version: '2'

services:
  website:
    depends_on:
      - postgres
    links:
      - postgres
    build: .
    ports:
      - '4000:4000'

  postgres:
    image: 'postgres:9.5'
    ports:
      - '5433:5433'
